theme: jekyll-theme-hacker
title: Competitive programming
show_downloads: false
description: This Repository contains solutions to Leetcode, Codechef... questions
plugins:
  - jemoji
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
